name: Block Nine
favicon: null
layout_spectrum: 0.24544
typography_spectrum: 0.89529
title: Construction Development Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9a9d96'
    - '#c6c9c2'
    - '#362d26'
    - '#0d0d0d'
    - '#584d49'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6155861227307469
purpose: []
